# Generated by Django 5.0.3 on 2024-03-16 16:28

import django.db.models.deletion
import websites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=1028, null=True)),
                ('category_order_num', models.IntegerField(default=99, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=2083, null=True)),
                ('task_reminder1_date', models.DateTimeField(blank=True, null=True)),
                ('task_reminder2_date', models.DateTimeField(blank=True, null=True)),
                ('task_due_date', models.DateTimeField(blank=True, null=True)),
                ('task_done', models.BooleanField(default=False)),
                ('task_created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_words', models.CharField(max_length=2083, null=True)),
                ('address', models.CharField(max_length=2083, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_click_date', models.DateTimeField(blank=True, null=True)),
                ('click_times', models.IntegerField(default=0, null=True)),
                ('website_image_url', models.CharField(blank=True, max_length=2083, null=True)),
                ('website_image', models.ImageField(blank=True, null=True, upload_to=websites.models.upload_location)),
                ('website_index_position_num', models.IntegerField(default=999, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websites.indexcategory')),
            ],
        ),
    ]
